chat-permission: "multichat.use"
chat-format: "%sender%: %message%"
chat-on: "Чат §aвключён"
chat-off: "Чат §cвыключен"
chatOnlyPlayers: "§cИспользовать мультичат может только игрок!"

redis:
  host: "127.0.0.1"
  port: 6379
  timeout: 3000
